import type { Metadata } from "next";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import Layout from "@/layout/index";
import { ThemeProvider } from "@/context/useTheme";

export const metadata: Metadata = {
	title: "Vadim Gierko",
	description: "Generated by create next app",
	icons: "https://vadimgierko.com/vadim-gerko-zdjecie-cv.jpg",
};

{
	/* <meta charSet="utf-8" />
				<meta name="viewport" content="initial-scale=1.0, width=device-width" />
				<meta name="author" content="Vadim Gierko" />
				<link
					rel="icon"
					href="https://vadimgierko.com/vadim-gerko-zdjecie-cv.jpg"
				/>
				*/
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="pl">
			<body>
				<ThemeProvider>
					<Layout>{children}</Layout>
				</ThemeProvider>
			</body>
		</html>
	);
}
