import type { Metadata } from "next";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import Layout from "@/layout/index";
import { ThemeProvider } from "@/context/useTheme";

export const metadata: Metadata = {
	title: "Vadim Gierko",
	description: "Generated by create next app",
	authors: { name: "Vadim Gierko" },
	icons: "https://vadimgierko.com/vadim-gerko-zdjecie-cv.jpg",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="pl">
			<body>
				<ThemeProvider>
					<Layout>{children}</Layout>
				</ThemeProvider>
			</body>
		</html>
	);
}
